COLUMNS = [
    "BILLING_PROVIDER_NPI_NUM",
    "SERVICING_PROVIDER_NPI_NUM",
    "HCPCS_CODE",
    "CLAIM_FROM_MONTH",
    "TOTAL_UNIQUE_BENEFICIARIES",
    "TOTAL_CLAIMS",
    "TOTAL_PAID",
]

SCHEMA_TEXT = f"Table: data\nColumns: {', '.join(COLUMNS)}"
